# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11a99a28cb73c6536fa47b48cc95f1b6204ad109132cae0021215390db41ab894ef9852ff5b5b947e73d7ebe9ae4dac38e67b7b315c5032b3a46277bf705a0f2

test:
  secret_key_base: 6e076e0969a470e1e7ec3b0de54ef7709673e26dae12ce8c1cc5b4b13522b7f2858532e3527f7babc15c7743bda3f5a36f8c516913ccc879d74f8dbb4d4d6726

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
